insert into app_role (code, name, description, created_at, updated_at)
values
    ('ADMIN', 'Administrator', 'Full system administration access', current_timestamp(6), current_timestamp(6)),
    ('RM', 'Relationship Manager', 'Maintain customer and application data', current_timestamp(6), current_timestamp(6)),
    ('ANALYST', 'Credit Analyst', 'Perform analyst review on credit application', current_timestamp(6), current_timestamp(6)),
    ('BRANCH_MANAGER', 'Branch Manager', 'Branch approval authority', current_timestamp(6), current_timestamp(6)),
    ('REGIONAL_HEAD', 'Regional Head', 'Regional escalation authority', current_timestamp(6), current_timestamp(6)),
    ('CREDIT_COMMITTEE', 'Credit Committee', 'Committee level decision authority', current_timestamp(6), current_timestamp(6)),
    ('BOARD_OF_DIRECTORS', 'Board of Directors', 'Board level decision authority', current_timestamp(6), current_timestamp(6)),
    ('WORKFLOW_ADMIN', 'Workflow Admin', 'Manage BPMN and approval routing', current_timestamp(6), current_timestamp(6))
on duplicate key update
    name = values(name),
    description = values(description),
    updated_at = values(updated_at);

insert into approval_rule (
    rule_id,
    rule_name,
    rule_type,
    metric_key,
    operator_key,
    threshold_value,
    action_routing,
    condition_expression,
    base_approver,
    escalated_approver,
    committee_approver,
    board_approver,
    justification_required,
    active_flag,
    message_template,
    created_at,
    updated_at
)
values
    (
        'RULE-001',
        'BMPK Limit Breach',
        'HARD_STOP',
        'AVAILABLE_LIMIT',
        'LT',
        0,
        'BOARD_OF_DIRECTORS',
        'IF Available Limit < 0 THEN hard stop',
        'BRANCH_MANAGER',
        'REGIONAL_HEAD',
        'CREDIT_COMMITTEE',
        'BOARD_OF_DIRECTORS',
        b'1',
        b'1',
        'Available limit is below zero ({actual})',
        current_timestamp(6),
        current_timestamp(6)
    ),
    (
        'RULE-002',
        'High DER',
        'DEVIATION',
        'DER',
        'GT',
        3.0000,
        'REGIONAL_HEAD',
        'IF DER > 3.0x THEN escalate to Regional Head',
        'BRANCH_MANAGER',
        'REGIONAL_HEAD',
        'CREDIT_COMMITTEE',
        'BOARD_OF_DIRECTORS',
        b'1',
        b'1',
        'Debt to equity ratio exceeds policy: {actual}',
        current_timestamp(6),
        current_timestamp(6)
    ),
    (
        'RULE-003',
        'Collateral Coverage Alert',
        'WARNING',
        'COLLATERAL_COVERAGE',
        'LT',
        100.0000,
        'CREDIT_COMMITTEE',
        'IF Collateral Coverage < 100% THEN escalate to Credit Committee',
        'BRANCH_MANAGER',
        'REGIONAL_HEAD',
        'CREDIT_COMMITTEE',
        'BOARD_OF_DIRECTORS',
        b'1',
        b'1',
        'Collateral coverage below 100%: {actual}',
        current_timestamp(6),
        current_timestamp(6)
    ),
    (
        'RULE-004',
        'Large Ticket Size',
        'WARNING',
        'PROPOSED_EXPOSURE',
        'GT',
        100000000000.0000,
        'BOARD_OF_DIRECTORS',
        'IF Total Plafon > 100 Miliar THEN Board approval',
        'BRANCH_MANAGER',
        'REGIONAL_HEAD',
        'CREDIT_COMMITTEE',
        'BOARD_OF_DIRECTORS',
        b'0',
        b'1',
        'Proposed exposure exceeds 100 billion',
        current_timestamp(6),
        current_timestamp(6)
    )
on duplicate key update
    rule_name = values(rule_name),
    rule_type = values(rule_type),
    metric_key = values(metric_key),
    operator_key = values(operator_key),
    threshold_value = values(threshold_value),
    action_routing = values(action_routing),
    condition_expression = values(condition_expression),
    base_approver = values(base_approver),
    escalated_approver = values(escalated_approver),
    committee_approver = values(committee_approver),
    board_approver = values(board_approver),
    justification_required = values(justification_required),
    active_flag = values(active_flag),
    message_template = values(message_template),
    updated_at = values(updated_at);
